# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-Gsm
version:      1.32
version_from: Gsm.pm
installdirs:  site
requires:
    Device::Modem:                 0
    Device::SerialPort:            0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
